version: '3.4'
services:
  web: 
    build:
      context: app
      dockerfile: Dockerfile
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5001:5001'
    volumes:
      - .:/app
    entrypoint: ["flask","run", "--host=0.0.0.0", "-p 5001"]
    # entrypoint: ["tail", "-f", "./app/app.py"]
