version: '3.4'
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5002:5002'
    volumes:
      - .:/app
    entrypoint: ["flask","run", "--host=0.0.0.0", "-p 5002"]
    # entrypoint: ["tail", "-f", "/dev/null"]
