name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t flask-web-experimento1 .  --tag flask-web-experimento1
    - name: Login Docker
      uses: 'lagren/docker-gcr-action@master'
      with:
        SERVICE_ACCOUNT_KEY: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
        HOST: 'gcr.io'
      run: |
        docker tag flask-app gcr.io/experimento1/flask-web-experimento1:v1.0
        docker push gcr.io/experimento1/flask-web-experimento1:v1.0
